// Generated by scripts/generate_mcq_data.js from assets/mcq-g*.md.
window.HPT_CHECKPOINTS = [
  {
    "id": "g01",
    "title": "G1 Hidden-Risk Baseline",
    "passTarget": 80,
    "source": "assets/mcq-g01-hidden-risk-baseline.md",
    "questions": [
      {
        "id": "g01-q01",
        "title": "Parked van at a crosswalk",
        "prompt": "You are driving on a residential street. A parked van sits close to a crosswalk, blocking your view of the curb and sidewalk behind it. Nothing is moving yet. What is the best hazard-perception response?",
        "choices": [
          "Ignore it until a pedestrian actually steps out",
          "Treat the van as a visible object that creates hidden space",
          "Move into the oncoming lane immediately to get a better view",
          "Speed up slightly so you spend less time beside the van"
        ],
        "answer": 1,
        "explanation": "The van itself is not the only issue. It blocks sightlines, so a pedestrian, cyclist, or child could appear from the hidden space around it.",
        "errorCategory": "Hidden-space recognition"
      },
      {
        "id": "g01-q02",
        "title": "Hedge-blocked driveway",
        "prompt": "You are approaching a driveway bordered by tall hedges. You cannot see whether a vehicle, cyclist, or pedestrian is about to exit. What should you predict?",
        "choices": [
          "A hidden actor could emerge from the driveway or sidewalk gap",
          "Nothing is there unless you can see it",
          "The hedge is the hazard only if it touches the road",
          "The safest move is to brake hard before every driveway"
        ],
        "answer": 0,
        "explanation": "A blocked driveway is a hidden-risk zone. The correct prediction is not that danger is certain, but that someone could emerge with little warning.",
        "errorCategory": "Driveway occlusion"
      },
      {
        "id": "g01-q03",
        "title": "Pause-and-predict before a curve",
        "prompt": "During a pause-and-predict exercise, the video is paused before a bend with parked cars near the outside of the curve. What is the most useful prediction?",
        "choices": [
          "The road will stay clear because no hazard is visible yet",
          "A hidden road user or vehicle may appear where the curve opens up",
          "The main risk is that your speedometer may be hard to read",
          "You should focus only on the center of your lane"
        ],
        "answer": 1,
        "explanation": "Curves reduce the view ahead. Parked cars near the bend add more blocked sightlines, so the next risk may appear only after the road opens.",
        "errorCategory": "Curve sightline prediction"
      },
      {
        "id": "g01-q04",
        "title": "Stopped delivery truck",
        "prompt": "You see a delivery truck stopped at the curb. Its rear doors are closed, and no one is visible. What is the best first gentle action?",
        "choices": [
          "Ease off the accelerator and prepare to cover the brake",
          "Honk before passing every stopped truck",
          "Steer sharply around it without checking mirrors",
          "Maintain speed because the truck is not moving"
        ],
        "answer": 0,
        "explanation": "The first response to hidden risk should usually be gentle and early: reduce speed slightly, increase readiness, and create time to react.",
        "errorCategory": "First gentle action"
      },
      {
        "id": "g01-q05",
        "title": "Gaps between parked cars",
        "prompt": "A row of parked cars lines the right side of the road. You notice gaps between two cars near a school zone. What should you be most alert for?",
        "choices": [
          "A tire mark on the road surface",
          "Whether all parked cars are the same color",
          "A hidden pedestrian or child stepping through the gap",
          "The exact model of each parked car"
        ],
        "answer": 2,
        "explanation": "Gaps between parked cars can hide people until they are close to the travel lane. The important cue is the hidden space, not the parked cars as objects.",
        "errorCategory": "Parked-vehicle occlusion"
      },
      {
        "id": "g01-q06",
        "title": "Replay reflection",
        "prompt": "You are replaying a clip after your first pass. On the first viewing, you noticed a parked SUV but did not slow mentally or physically. On replay, what should you ask yourself at that moment?",
        "choices": [
          "How new is the SUV?",
          "Would the SUV driver be legally responsible for everything?",
          "Can I memorize the exact second when the hazard appears?",
          "What hidden space does this visible object create?"
        ],
        "answer": 3,
        "explanation": "Replay is for improving prediction. The key habit is linking visible blockers to possible hidden actors before they appear.",
        "errorCategory": "Pause-and-predict reflection"
      },
      {
        "id": "g01-q07",
        "title": "Bus blocking a crosswalk",
        "prompt": "A bus is stopped ahead near an intersection. You cannot see the crosswalk on the far side of the bus. What is the safest interpretation?",
        "choices": [
          "The bus is large, so it protects you from pedestrians",
          "The only hazard is traffic behind you",
          "You should accelerate before the bus pulls out",
          "A pedestrian may be hidden by the bus and enter your path"
        ],
        "answer": 3,
        "explanation": "Large vehicles create major blind zones. The risk is not just the bus moving, but people or vehicles hidden by it.",
        "errorCategory": "Large-vehicle occlusion"
      },
      {
        "id": "g01-q08",
        "title": "Baseline hidden-risk thinking",
        "prompt": "You are driving past a residential block with parked cars, hedges, and several driveways. Nothing has moved into your lane. Which response best shows hidden-risk baseline thinking?",
        "choices": [
          "Keep your eyes fixed straight ahead because the lane is clear",
          "Brake hard at every parked car so no prediction is needed",
          "Scan for blocked sightlines, ease speed, and prepare for a possible emergence",
          "Wait until a hazard appears, then make one sudden correction"
        ],
        "answer": 2,
        "explanation": "Hidden-risk driving means identifying where hazards could emerge before they become obvious. The goal is early, smooth preparation rather than late reaction.",
        "errorCategory": "Baseline hidden-risk scanning"
      }
    ]
  },
  {
    "id": "g02",
    "title": "G2 Residential Sightlines and Space",
    "passTarget": 80,
    "source": "assets/mcq-g02-residential-sightlines-and-space.md",
    "questions": [
      {
        "id": "g02-q01",
        "title": "Potential or developing?",
        "prompt": "You are driving down a residential street. A parked car is ahead on the right. Nothing is moving yet, but the car blocks your view of the sidewalk and curb area. How should you classify it right now?",
        "choices": [
          "No hazard, because it is parked",
          "Developing hazard, because every parked car requires immediate braking",
          "Emergency hazard, because you must stop before passing it",
          "Potential hazard, because it could hide a person, bike, door, or driveway movement"
        ],
        "answer": 3,
        "explanation": "A parked car that blocks sightlines is a potential hazard. It becomes developing when a concrete cue appears, such as a door opening, a person stepping out, wheels turning, or a vehicle backing out.",
        "errorCategory": "Potential-vs-developing timing"
      },
      {
        "id": "g02-q02",
        "title": "Door opening",
        "prompt": "A parked car ahead has been a potential hazard. As you approach, you see the driver's door crack open into your lane. What has changed?",
        "choices": [
          "It is still only potential, because the door is not fully open",
          "It is no longer a hazard, because the driver has seen you",
          "It is now a developing hazard, because it has started to affect your path",
          "It only matters if there is oncoming traffic"
        ],
        "answer": 2,
        "explanation": "A developing hazard is one that has started to change your driving plan. A door opening is the cue that turns \"could happen\" into \"act now.\"",
        "errorCategory": "Developing-hazard recognition"
      },
      {
        "id": "g02-q03",
        "title": "Ball between parked cars",
        "prompt": "You see a ball roll from between two parked cars into the street. You do not yet see a child. What is the best first response?",
        "choices": [
          "Ease off the accelerator, cover the brake, and scan the hidden space between the cars",
          "Maintain speed until a child appears",
          "Honk and keep your lane position",
          "Move sharply left immediately"
        ],
        "answer": 0,
        "explanation": "Children are unpredictable residential hazards. The ball is a clue that a hidden child may enter the road, so the response should begin before the child is visible.",
        "errorCategory": "Hidden-actor prediction"
      },
      {
        "id": "g02-q04",
        "title": "Backing out of a driveway",
        "prompt": "You are passing a row of parked cars and a driveway is partly blocked by a tall hedge. You notice the rear of a vehicle beginning to appear from the driveway. What should you do?",
        "choices": [
          "Treat it as potential until the whole vehicle is in the road",
          "Speed up to clear the driveway before the car backs out",
          "Move right to make more room for oncoming traffic",
          "Treat it as developing and prepare to slow or stop"
        ],
        "answer": 3,
        "explanation": "Once movement begins from a hidden driveway, the hazard is developing because it can enter your path.",
        "errorCategory": "Driveway hazard timing"
      },
      {
        "id": "g02-q05",
        "title": "Passing a parked car",
        "prompt": "A parked car is on the right side of a residential street. There is no lane line, but there is enough room and no oncoming traffic. What lane position best manages the risk?",
        "choices": [
          "Stay close to the parked car to leave more room for imaginary oncoming traffic",
          "Drive in the middle of the street until the road is completely clear",
          "Move left smoothly and leave about 3 to 4 feet of side clearance",
          "Stop behind every parked car before passing"
        ],
        "answer": 2,
        "explanation": "The lane positioning lesson says to imagine the lane moving left around a parked car and to leave side clearance because a door could open at any moment.",
        "errorCategory": "Side clearance"
      },
      {
        "id": "g02-q06",
        "title": "Following distance",
        "prompt": "You are following another car on a residential street. The lead car passes a mailbox. You reach the mailbox one second later. What is the safest correction?",
        "choices": [
          "Keep the gap because residential speeds are low",
          "Move closer so no one cuts in",
          "Increase the gap until you have about a 3 to 4 second cushion",
          "Watch only the brake lights and ignore fixed-object timing"
        ],
        "answer": 2,
        "explanation": "Fixed-object counting turns following distance into a measurable habit. In residential driving, the course target is about a 3 to 4 second cushion.",
        "errorCategory": "Following distance"
      },
      {
        "id": "g02-q07",
        "title": "Visual lead time",
        "prompt": "A new driver keeps looking at the pavement directly in front of the hood and makes small steering corrections every few seconds. What should they do instead?",
        "choices": [
          "Aim high, look 10 to 15 seconds ahead, and scan the big picture",
          "Look only at the parked cars on the right",
          "Watch the center mirror continuously",
          "Grip the wheel tighter and steer more often"
        ],
        "answer": 0,
        "explanation": "Looking 10 to 15 seconds ahead improves lane position and reveals potential hazards earlier.",
        "errorCategory": "Visual lead time"
      },
      {
        "id": "g02-q08",
        "title": "Curve as occlusion",
        "prompt": "You approach a sharp residential curve with parked cars near the outside of the bend. You cannot see what is around the curve. What is the safest interpretation?",
        "choices": [
          "The curve is only a steering task",
          "The curve is an occlusion that may hide a pedestrian, vehicle, bike, or parked car",
          "The curve is safe if there is no yellow centerline",
          "The curve matters only if the road is wet"
        ],
        "answer": 1,
        "explanation": "A curve is a blocked sightline. The important hazard may be beyond what you can see.",
        "errorCategory": "Curve occlusion"
      },
      {
        "id": "g02-q09",
        "title": "Speed before a curve",
        "prompt": "You are approaching a residential curve. The road looks clear up to the bend, but the view beyond it is blocked. What is the best speed plan?",
        "choices": [
          "Maintain speed into the curve and brake only if something appears",
          "Accelerate into the curve to reduce time in the blind area",
          "Drift left to increase the turning radius",
          "Check the rearview mirror, slow before the curve, then gently accelerate out as the view opens"
        ],
        "answer": 3,
        "explanation": "Slow before the curve, check behind before slowing, and accelerate gently only as the view opens and the vehicle straightens.",
        "errorCategory": "Speed before occlusion"
      },
      {
        "id": "g02-q10",
        "title": "Cyclist near parked cars",
        "prompt": "You are on a narrow residential street. A cyclist is ahead near parked cars, and an oncoming car is approaching. What is the best decision?",
        "choices": [
          "Squeeze between the cyclist and oncoming car because you have space",
          "Hold back, keep following distance, and pass only when you can leave safe side clearance",
          "Honk so the cyclist moves closer to the parked cars",
          "Pass close to the cyclist but stay far from the oncoming car"
        ],
        "answer": 1,
        "explanation": "Parked cars can hide doors or force a cyclist to move left. Preserve side clearance and wait if the available space disappears.",
        "errorCategory": "Space cushion and lane position"
      }
    ]
  },
  {
    "id": "g03",
    "title": "G3 Intersection Scanning Ladder",
    "passTarget": 80,
    "source": "assets/mcq-g03-intersection-scanning-ladder.md",
    "questions": [
      {
        "id": "g03-q01",
        "title": "Blocked two-way stop",
        "prompt": "You stop at a residential stop sign. The cross street has no stop signs, and parked cars make it hard to see traffic coming from your left. What should you do before entering?",
        "choices": [
          "Look straight ahead, then accelerate because you stopped completely",
          "Check your rearview mirror, then enter if no one is behind you",
          "Move quickly so cross traffic has time to react",
          "Check left-right-left, inch forward until you can see past the parked cars, then check again"
        ],
        "answer": 3,
        "explanation": "A full stop is not enough when sightlines are blocked. Use left-right-left, creep forward to improve the view, then rescan before entering.",
        "errorCategory": "Blind intersection / blocked edge"
      },
      {
        "id": "g03-q02",
        "title": "Uncontrolled residential intersection",
        "prompt": "You approach an uncontrolled residential intersection where no signs or signals are posted. A car is approaching from your right at about the same time. What is the safest response?",
        "choices": [
          "Continue because you are on the wider-looking street",
          "Speed up to clear the intersection first",
          "Slow, scan both directions, and be prepared to yield to the vehicle on your right",
          "Stop only if the other driver honks or brakes"
        ],
        "answer": 2,
        "explanation": "At an uncontrolled intersection, the driver on the left generally yields to the driver on the right, but the safety task is still to slow and scan for conflicts.",
        "errorCategory": "Right-of-way fixation"
      },
      {
        "id": "g03-q03",
        "title": "Hedge at the corner",
        "prompt": "You are turning right from a residential street. A sidewalk runs along both sides, and a hedge blocks your view of the corner. What should be included in your traffic check?",
        "choices": [
          "Left for traffic, right for pedestrians and cyclists, then left again before moving",
          "Only the lane you are entering, because pedestrians will stop",
          "Rearview mirror only, because the turn is low speed",
          "The traffic signal on the nearest major street"
        ],
        "answer": 0,
        "explanation": "A right turn still requires checking cross traffic and the pedestrian/cyclist zone near the corner, especially when landscaping blocks the edge.",
        "errorCategory": "Pedestrian / cyclist zone"
      },
      {
        "id": "g03-q04",
        "title": "Crossing a major street",
        "prompt": "At a two-way stop, you are stopped on the minor street and plan to go straight across a major street. Cross traffic does not have stop signs. What is the main hazard-perception task?",
        "choices": [
          "Watch only the first lane of traffic nearest you",
          "Enter halfway and wait in the middle if needed",
          "Follow the car ahead as soon as it starts moving",
          "Check for a gap across all lanes you must cross, including traffic from both directions"
        ],
        "answer": 3,
        "explanation": "Crossing a major street expands the conflict area. You need a gap that covers every lane and direction you will cross, not just the nearest lane.",
        "errorCategory": "Major-street expansion"
      },
      {
        "id": "g03-q05",
        "title": "Pedestrian at an all-way stop",
        "prompt": "You reach an all-way stop after another car on your right has already stopped. A pedestrian is stepping toward the crosswalk on your left. What should you do?",
        "choices": [
          "Yield to the pedestrian and resolve vehicle order only after the crosswalk is clear",
          "Go first because you are turning right",
          "Wave the other car through and ignore the pedestrian until you move",
          "Enter slowly so the pedestrian knows to wait"
        ],
        "answer": 0,
        "explanation": "Pedestrian conflict takes priority. Right-of-way order between vehicles does not remove the need to yield to a pedestrian entering or using the crosswalk.",
        "errorCategory": "Pedestrian / right-of-way sequencing"
      },
      {
        "id": "g03-q06",
        "title": "Second viewing position",
        "prompt": "You are approaching a residential intersection with a stop sign. A van parked close to the corner blocks your view to the right. What is the best technique?",
        "choices": [
          "Stop at the line, then enter if you cannot hear traffic",
          "Stop, scan left-center-right, move forward slowly to a better viewing point, and rescan",
          "Pull out quickly so your vehicle becomes visible",
          "Focus only on the direction you plan to turn"
        ],
        "answer": 1,
        "explanation": "The first stop satisfies the control, but the second viewing position helps solve the blocked sightline. Inching should be slow enough to stop again.",
        "errorCategory": "Blind intersection / inching"
      },
      {
        "id": "g03-q07",
        "title": "Far edge hidden by SUV",
        "prompt": "You are crossing a major street from a side street. The nearest lane is clear, but a large SUV in the far lane blocks your view of a bike lane and sidewalk beyond it. What should you assume?",
        "choices": [
          "The blocked area may hide a cyclist, pedestrian, or vehicle, so you need a better view before crossing",
          "The far edge is clear because cars are stopped",
          "Only cars count as cross traffic",
          "If the SUV driver waves, the crossing is safe"
        ],
        "answer": 0,
        "explanation": "Blocked edges hide smaller and faster-moving hazards. A wave or a partial gap does not confirm the whole crossing path is clear.",
        "errorCategory": "Blocked edge / vulnerable road user"
      },
      {
        "id": "g03-q08",
        "title": "Left turn at a four-way stop",
        "prompt": "You stop at a four-way stop at the same time as a driver directly across from you. You plan to turn left, and the other driver appears to be going straight. What should you do?",
        "choices": [
          "Turn left first because you stopped at the same time",
          "Focus only on the other driver and ignore the crosswalks",
          "Yield to the oncoming driver going straight, while continuing to scan for pedestrians and cross traffic",
          "Enter the intersection and wait for the other driver to stop again"
        ],
        "answer": 2,
        "explanation": "When arrival time is equal, the left-turning driver yields to oncoming traffic going straight. Scanning still includes crosswalks and late arrivals.",
        "errorCategory": "All-way stop / left-turn yield"
      },
      {
        "id": "g03-q09",
        "title": "Hidden right-side traffic",
        "prompt": "You are preparing to enter a busy major street from a residential side street. Traffic from the left is clear, but traffic from the right is hidden by a curve and parked vehicles. What is the safest decision?",
        "choices": [
          "Go because the first direction you checked is clear",
          "Wait or inch forward only enough to improve your view, then complete another left-right-left scan",
          "Turn on your signal and expect traffic to make space",
          "Look straight ahead and listen for engines"
        ],
        "answer": 1,
        "explanation": "The scan is not complete if one side is hidden. You need a usable view of both directions before committing to the crossing or turn.",
        "errorCategory": "Incomplete scan / cross traffic"
      },
      {
        "id": "g03-q10",
        "title": "Green light on a major street",
        "prompt": "You approach an intersection on a major street with a green light. A car is waiting to turn left across your path, and pedestrians are near the far crosswalk. What should your scan include?",
        "choices": [
          "Only the green light, because it gives you the right-of-way",
          "Only the car turning left, because pedestrians are not in your lane yet",
          "Only the vehicle behind you, because braking is the main risk",
          "Left-center-right scanning across the intersection, including the turning car, crosswalks, and road edges"
        ],
        "answer": 3,
        "explanation": "A green light does not remove conflict checks. On major streets, the scan must widen to include turning vehicles, crosswalks, and edge movement.",
        "errorCategory": "Major-street intersection scanning"
      }
    ]
  },
  {
    "id": "g04",
    "title": "G4 Conflict Checks Around the Car",
    "passTarget": 80,
    "source": "assets/mcq-g04-conflict-checks-around-the-car.md",
    "questions": [
      {
        "id": "g04-q01",
        "title": "Creeping side-street driver",
        "prompt": "You are driving on a major street. A car is waiting at a stop sign on a side street to your right. You have legal right-of-way, but the driver is creeping forward.",
        "choices": [
          "Continue at the same speed because you have right-of-way",
          "Cover the brake, check surrounding traffic, and be ready to slow",
          "Move left without checking mirrors",
          "Honk immediately and maintain speed"
        ],
        "answer": 1,
        "explanation": "Legal right-of-way does not remove the need to manage risk. A creeping vehicle may enter your path.",
        "errorCategory": "Right-of-way fixation"
      },
      {
        "id": "g04-q02",
        "title": "Unclear left-turn intent",
        "prompt": "You approach an intersection on a major road. An opposing vehicle is waiting to turn left across your path. The driver appears to be looking past you, not at you.",
        "choices": [
          "Assume the driver sees you because you are on the major road",
          "Reduce risk by checking mirrors, easing off the accelerator, and preparing to brake",
          "Speed up to clear the intersection first",
          "Move toward the centerline to make yourself more visible"
        ],
        "answer": 1,
        "explanation": "Right-of-way is not enough when another driver's attention or intent is uncertain.",
        "errorCategory": "Legal priority vs practical safety"
      },
      {
        "id": "g04-q03",
        "title": "Right turn on red with side pedestrians",
        "prompt": "You stop at a red light and plan to turn right. The crosswalk to your right looks clear, but pedestrians are approaching from behind your right shoulder.",
        "choices": [
          "Check the crosswalk, right-side blind area, and bike lane before moving",
          "Turn as soon as the vehicle lane is clear",
          "Check left for traffic only, then turn",
          "Stop only if someone is already inside the crosswalk"
        ],
        "answer": 0,
        "explanation": "Right turn on red creates traps for pedestrians approaching from the side or behind.",
        "errorCategory": "Pedestrian trap"
      },
      {
        "id": "g04-q04",
        "title": "Cyclist in the bike lane",
        "prompt": "You are stopped at a red light with your right signal on. A cyclist is coming up in the bike lane on your right.",
        "choices": [
          "Turn before the cyclist reaches you",
          "Turn wide into the next lane",
          "Wait and let the cyclist pass before turning",
          "Edge into the bike lane to block the cyclist"
        ],
        "answer": 2,
        "explanation": "A cyclist on the right can be hidden or easy to miss during right turns. Yield before turning.",
        "errorCategory": "Cyclist conflict"
      },
      {
        "id": "g04-q05",
        "title": "Stale mirror information",
        "prompt": "You are preparing for a right turn across a marked bike lane. You checked your mirror five seconds ago and saw no cyclist.",
        "choices": [
          "Turn because the mirror was clear recently",
          "Check mirror and shoulder again before crossing the bike lane",
          "Signal and rely on cyclists to yield",
          "Move halfway into the bike lane without checking"
        ],
        "answer": 1,
        "explanation": "Bike lane conditions can change quickly. A fresh mirror and shoulder check is needed before crossing.",
        "errorCategory": "Stale mirror information"
      },
      {
        "id": "g04-q06",
        "title": "Mirror before braking",
        "prompt": "You see traffic slowing ahead. Before braking firmly, what should you do if time allows?",
        "choices": [
          "Check only the speedometer",
          "Look at the right mirror only",
          "Brake first, then check behind you",
          "Check the rearview mirror for following distance"
        ],
        "answer": 3,
        "explanation": "A rearview check helps you judge whether a tailgater changes how gradually you should slow.",
        "errorCategory": "Rear risk awareness"
      },
      {
        "id": "g04-q07",
        "title": "Tailgater at a yellow light",
        "prompt": "You notice a vehicle following too closely behind you. A stale yellow light appears ahead.",
        "choices": [
          "Brake hard to make the stop",
          "Accelerate aggressively through the light",
          "Check conditions, begin slowing early if stopping is needed, and avoid sudden braking",
          "Ignore the vehicle behind because it is their responsibility"
        ],
        "answer": 2,
        "explanation": "You still must obey the signal, but a tailgater requires earlier, smoother communication through braking.",
        "errorCategory": "Tailgater management"
      },
      {
        "id": "g04-q08",
        "title": "Mirror vs shoulder check",
        "prompt": "You want to move right into the next lane. Your side mirror appears clear.",
        "choices": [
          "Check the mirror, signal, then perform a shoulder check before moving",
          "Move over because mirrors show the full lane",
          "Signal and move gradually without another check",
          "Turn your head only and ignore the mirror"
        ],
        "answer": 0,
        "explanation": "Mirrors help, but they do not eliminate blind zones. A shoulder check confirms the space beside you.",
        "errorCategory": "Mirror overreliance"
      },
      {
        "id": "g04-q09",
        "title": "Vehicle disappears from mirror",
        "prompt": "You are changing lanes left. A car behind you in the target lane disappears from your side mirror.",
        "choices": [
          "It must have slowed down, so continue changing lanes",
          "It must be directly behind you, so speed up",
          "It is no longer relevant because it is not visible",
          "It is probably in your blind zone, so do not move until you confirm its position"
        ],
        "answer": 3,
        "explanation": "A vehicle that disappears from the mirror may be beside you in the blind spot.",
        "errorCategory": "Blind-zone tracking"
      },
      {
        "id": "g04-q10",
        "title": "Busy right turn",
        "prompt": "You are preparing to turn right from a busy street. There is a crosswalk, a bike lane, and a vehicle close behind you.",
        "choices": [
          "Check rearview mirror, right mirror, right shoulder, bike lane, and crosswalk before turning",
          "Check only the traffic coming from the left",
          "Focus only on the signal light",
          "Turn slowly and let others react"
        ],
        "answer": 0,
        "explanation": "Right turns require checking rear risk, side blind zones, bike-lane traffic, and pedestrians.",
        "errorCategory": "Incomplete conflict scan"
      }
    ]
  },
  {
    "id": "g05",
    "title": "G5 Lane Change Deep Dive",
    "passTarget": 80,
    "source": "assets/mcq-g05-lane-change-deep-dive.md",
    "questions": [
      {
        "id": "g05-q01",
        "title": "Lane-change sequence",
        "prompt": "You are preparing to move one lane left on a multi-lane road. Traffic ahead is steady, and the left lane appears open. What is the best sequence before changing lanes?",
        "choices": [
          "Check the mirror, move left, then signal once you are halfway over",
          "Look over your shoulder first, then signal only if another driver is nearby",
          "Speed up, signal, and move left before the gap closes",
          "Signal, check mirrors, quick over-the-shoulder check, then go only if clear"
        ],
        "answer": 3,
        "explanation": "SMOG means Signal, Mirror, Over the shoulder, Go. The signal communicates intent, but mirrors and a blind spot check still decide whether the move is safe.",
        "errorCategory": "SMOG sequence"
      },
      {
        "id": "g05-q02",
        "title": "Signal is not priority",
        "prompt": "You turn on your left signal to change lanes. A driver in the left lane is slightly behind you but still far enough back that the move might work. What should you do next?",
        "choices": [
          "Move left immediately because your signal gives you priority",
          "Cancel the signal because signaling might make the other driver speed up",
          "Keep signaling while checking mirrors, blind spot, and whether the gap stays stable",
          "Brake hard so the driver in the left lane has to pass you"
        ],
        "answer": 2,
        "explanation": "The signal is a warning and request for attention, not permission to move. You still need to confirm the space beside and behind you before going.",
        "errorCategory": "Signal timing"
      },
      {
        "id": "g05-q03",
        "title": "Missing blind-spot confirmation",
        "prompt": "Your left mirror shows no vehicle next to you, and the lane beside you looks open. What is the missing check before you begin moving left?",
        "choices": [
          "A quick chin-to-shoulder check into the left blind spot",
          "A long look over your shoulder until the lane change is complete",
          "A check of the right mirror because you are moving left",
          "A honk to warn drivers that you are entering the lane"
        ],
        "answer": 0,
        "explanation": "Mirrors do not prove the blind spot is empty. A quick chin-to-shoulder check confirms the hidden side zone without taking your eyes away from the road for too long.",
        "errorCategory": "Blind spot check"
      },
      {
        "id": "g05-q04",
        "title": "Staring over the shoulder",
        "prompt": "During a left lane change, you look over your shoulder for several seconds and the car starts drifting before you are ready. What should you change?",
        "choices": [
          "Turn your whole body farther so you can see more of the left lane",
          "Use a quick chin-to-shoulder glance, then bring your eyes forward before easing over",
          "Keep both hands rigid and stare over your shoulder until the lane is clear",
          "Skip the shoulder check and trust the mirror instead"
        ],
        "answer": 1,
        "explanation": "The shoulder check should be quick. Staring over the shoulder can pull your arms and steering, and it also keeps you from watching what is happening ahead.",
        "errorCategory": "Overlong shoulder check"
      },
      {
        "id": "g05-q05",
        "title": "Gap stability",
        "prompt": "You see a gap in the left lane, but the car behind that gap is slowly gaining on you. The lane is technically open right now. What is the safest decision?",
        "choices": [
          "Start moving left because the gap is open at this moment",
          "Move left faster so you finish before the other car arrives",
          "Signal longer, which makes the other driver responsible for slowing down",
          "Wait, because the gap may close before your lane change is complete"
        ],
        "answer": 3,
        "explanation": "A safe lane change needs a stable gap, not just a clear snapshot. If another vehicle is closing, the space may disappear while you are moving over.",
        "errorCategory": "Gap stability"
      },
      {
        "id": "g05-q06",
        "title": "Closing speed",
        "prompt": "A car in the left mirror looks small and far away, but each time you check, it appears noticeably closer. What is the main hazard?",
        "choices": [
          "The car is probably parked on the shoulder",
          "The car is far away, so it cannot affect your decision",
          "The car's closing speed may make the lane change unsafe",
          "The mirror is unreliable, so only the blind spot matters"
        ],
        "answer": 2,
        "explanation": "Distance alone is not enough. If a vehicle is approaching quickly, it can reach your target gap before you complete a smooth lane change.",
        "errorCategory": "Closing speed"
      },
      {
        "id": "g05-q07",
        "title": "Smooth movement",
        "prompt": "You have signaled, checked your mirrors, checked your blind spot, and confirmed a stable gap. How should you move into the left lane?",
        "choices": [
          "Ease over smoothly across several seconds while continuing to monitor traffic",
          "Make one quick steering input so you spend less time between lanes",
          "Drift left without steering so the move feels natural",
          "Brake while moving left so vehicles behind you have more time"
        ],
        "answer": 0,
        "explanation": "A lane change should be controlled and gradual. Smooth movement over several seconds gives you time to track the gap and avoid abrupt steering.",
        "errorCategory": "Smooth lane movement"
      },
      {
        "id": "g05-q08",
        "title": "Abort option",
        "prompt": "You begin a left lane change after checking that the gap is open. Halfway through, a vehicle in the left lane speeds up and the space starts closing. What should you do?",
        "choices": [
          "Continue because you already started the lane change",
          "Abort the lane change if it is safer to return to your original lane",
          "Accelerate sharply and force your way into the lane",
          "Stop between the two lanes until the other driver passes"
        ],
        "answer": 1,
        "explanation": "Starting a lane change does not mean you must finish it. A good lane-change plan includes an abort option if the gap changes.",
        "errorCategory": "Abort decision"
      }
    ]
  },
  {
    "id": "g06",
    "title": "G6 High-Speed, Large-Vehicle, Low-Visibility Driving",
    "passTarget": 80,
    "source": "assets/mcq-g06-high-speed-large-vehicle-low-visibility.md",
    "questions": [
      {
        "id": "g06-q01",
        "title": "Freeway merge gap",
        "prompt": "You are on a freeway on-ramp. Traffic in the right lane is moving faster than you, and a white van is closing from behind in the lane you need. What is the safest decision?",
        "choices": [
          "Signal, accelerate to match traffic, check mirrors and blind spot, and use a gap that will not force others to brake",
          "Merge immediately because ramp traffic has priority",
          "Slow sharply at the end of the ramp and wait for traffic to clear",
          "Move halfway into the lane so traffic will make space"
        ],
        "answer": 0,
        "explanation": "Freeway traffic already has the right-of-way. A safe merge depends on matching speed, checking mirrors and blind spots, and entering only when the gap is stable.",
        "errorCategory": "Freeway merge gap"
      },
      {
        "id": "g06-q02",
        "title": "Two-lane-over movement",
        "prompt": "You want to change lanes on the freeway. The lane beside you looks open, but a car two lanes over is drifting toward the same space. What should you do?",
        "choices": [
          "Change lanes because the lane directly beside you is clear",
          "Speed up and claim the space before the other car gets there",
          "Check several lanes across, hold your lane, and wait until the shared gap is clearly stable",
          "Signal longer, then move over without another shoulder check"
        ],
        "answer": 2,
        "explanation": "At freeway speed, the hazard may come from more than one lane away. Blind spot checks should include the adjacent lane and vehicles that could move into the same gap.",
        "errorCategory": "Lane-change blind zone"
      },
      {
        "id": "g06-q03",
        "title": "Lane-change commitment",
        "prompt": "You signaled for a lane change, checked your mirror, and started to move left. Suddenly the lead vehicle in your current lane brakes. What matters most before you continue?",
        "choices": [
          "Whether your signal has been on for 4 to 5 seconds",
          "Whether the lane you are entering has a higher speed limit",
          "Whether you still have forward space, a clear blind spot, and room to abort",
          "Whether the driver behind you understands your plan"
        ],
        "answer": 2,
        "explanation": "A lane change is not safe just because the signal is on. You need a clear gap, blind spot confirmation, forward space, and an escape option.",
        "errorCategory": "Lane-change commitment"
      },
      {
        "id": "g06-q04",
        "title": "Being passed",
        "prompt": "A faster vehicle begins passing you on the left. You are already near the speed limit and your lane is clear. What should you do?",
        "choices": [
          "Speed up so the passing driver cannot cut in front of you",
          "Drift left slightly to remind the driver you are there",
          "Brake hard as soon as the vehicle reaches your rear quarter",
          "Maintain a predictable path and yield the space needed for the pass to complete safely"
        ],
        "answer": 3,
        "explanation": "When being passed, the safest action is to be predictable and allow the pass to finish. Competing for the space increases conflict at high speed.",
        "errorCategory": "Being passed"
      },
      {
        "id": "g06-q05",
        "title": "Canyon sightline",
        "prompt": "You are driving on a narrow canyon road. A sharp bend ahead hides the next stretch of road, and there is no shoulder. What is the best hazard-perception response?",
        "choices": [
          "Keep your speed because you have not seen another vehicle yet",
          "Move toward the centerline to see around the curve earlier",
          "Tap the brakes only after you see a vehicle coming toward you",
          "Slow before the bend, stay in your lane, and prepare for hidden oncoming traffic or stopped traffic"
        ],
        "answer": 3,
        "explanation": "On canyon roads, the bend itself is the hazard because it hides what matters. Speed and lane position should be adjusted before the hidden area appears.",
        "errorCategory": "Canyon sightline"
      },
      {
        "id": "g06-q06",
        "title": "Canyon turnout",
        "prompt": "You are driving below the speed limit on a canyon road because conditions are difficult. Five vehicles have formed a line behind you, and a turnout appears ahead. What should you do?",
        "choices": [
          "Keep going because slower traffic always has priority on narrow roads",
          "Stop in the travel lane and wave the other cars around",
          "Pull into the turnout when safe, let traffic pass, then check carefully before re-entering",
          "Speed up through the next curves so the line behind you clears"
        ],
        "answer": 2,
        "explanation": "A slow vehicle with five or more vehicles behind it should use a turnout when safe. Re-entering requires a fresh signal, mirror check, shoulder check, and safe gap.",
        "errorCategory": "Canyon turnout"
      },
      {
        "id": "g06-q07",
        "title": "Truck No-Zone",
        "prompt": "You are driving beside a large truck on the freeway. You cannot see the truck driver's face in the truck's side mirror. What does that mean?",
        "choices": [
          "The truck driver can still see you because the truck is higher",
          "You are likely in a No-Zone and should either pass efficiently or drop back",
          "You should stay there because trucks move slowly and predictably",
          "You should honk so the truck driver knows you are beside them"
        ],
        "answer": 1,
        "explanation": "If you cannot see the driver's face in the mirror, the driver likely cannot see you. Lingering beside a truck leaves you exposed if it moves, drifts, or is affected by wind.",
        "errorCategory": "Truck blind zone"
      },
      {
        "id": "g06-q08",
        "title": "Truck wide turn",
        "prompt": "A large truck ahead signals right but swings left before the turn. There is space between the truck and the curb. What should you do?",
        "choices": [
          "Drive into the open space before the truck completes the turn",
          "Pass on the right if you can clear the truck before the crosswalk",
          "Move close behind the truck so other drivers do not cut in",
          "Stay back and give the truck room to complete the wide turn"
        ],
        "answer": 3,
        "explanation": "Large vehicles need extra turning room and may swing wide. The space beside a turning truck can disappear quickly.",
        "errorCategory": "Truck turning room"
      },
      {
        "id": "g06-q09",
        "title": "Night glare",
        "prompt": "You are driving at night on a two-lane road. Oncoming headlights are causing glare, and the lane edge is harder to read. What is the safest adjustment?",
        "choices": [
          "Stare directly at the oncoming headlights until the car passes",
          "Reduce speed, avoid staring into the glare, and use lane edges and shoulder movement to guide your search",
          "Increase speed so you spend less time in the glare",
          "Turn on high beams while the other car is approaching"
        ],
        "answer": 1,
        "explanation": "Glare reduces night vision and search quality. Slowing and scanning road edges and shoulders gives more time to detect curves, pedestrians, animals, or stopped vehicles.",
        "errorCategory": "Night glare"
      },
      {
        "id": "g06-q10",
        "title": "Wet low-visibility freeway",
        "prompt": "It is raining on the freeway. Spray from traffic reduces visibility, and the road surface is wet. What should change first?",
        "choices": [
          "Increase following distance, reduce speed early, and make steering and braking inputs gentler",
          "Follow closer so other vehicles block the spray",
          "Keep normal speed but brake harder if traffic slows",
          "Move into the fastest lane because it usually has fewer trucks"
        ],
        "answer": 0,
        "explanation": "Wet and low-visibility conditions reduce both traction and seeing distance. The same hazards require earlier speed reduction, longer space cushions, and smoother control.",
        "errorCategory": "Wet low-visibility adjustment"
      }
    ]
  },
  {
    "id": "g07",
    "title": "G7 U.S. Simulator Set",
    "passTarget": 80,
    "source": "assets/mcq-g07-us-simulator-set.md",
    "questions": [
      {
        "id": "g07-q01",
        "title": "When to click",
        "prompt": "You are watching a hazard-perception simulator clip. A road user is visible near the edge of the scene but has not yet started moving into your path. When should you click?",
        "choices": [
          "As soon as the road user first appears anywhere on screen",
          "Repeatedly every few seconds until something happens",
          "Only when the road user begins to create a developing hazard for your path",
          "At the end of the clip after confirming what happened"
        ],
        "answer": 2,
        "explanation": "The click should mark the moment a possible hazard becomes relevant to your driving path, not every visible object.",
        "errorCategory": "Timing"
      },
      {
        "id": "g07-q02",
        "title": "Missed occlusion cue",
        "prompt": "You miss a simulator hazard because a vehicle emerged from behind a parked vehicle. What is the best debrief note?",
        "choices": [
          "I missed an occlusion cue and should scan blocked sightlines earlier",
          "I need to memorize this exact clip",
          "The simulator was unfair because the hazard was not visible at first",
          "I should click every time I see a parked vehicle"
        ],
        "answer": 0,
        "explanation": "The useful lesson is that parked or stopped vehicles can hide road users. The next attempt should focus on recognizing blocked sightlines earlier.",
        "errorCategory": "Occlusion"
      },
      {
        "id": "g07-q03",
        "title": "Pattern clicking",
        "prompt": "During a simulator attempt, you click whenever you see any pedestrian, cyclist, driveway, parked car, or intersection. Your score does not improve. What is the likely problem?",
        "choices": [
          "You are waiting too long every time",
          "You are pattern clicking instead of identifying developing hazards",
          "You are not clicking enough objects",
          "You should ignore pedestrians unless they enter the lane"
        ],
        "answer": 1,
        "explanation": "Pattern clicking creates noise. A good click is tied to a change in risk: movement, intent, conflict path, reduced space, or blocked view becoming relevant.",
        "errorCategory": "Pattern clicking"
      },
      {
        "id": "g07-q04",
        "title": "Over-focus",
        "prompt": "A vehicle ahead slows slightly near a side street. You focus on it so closely that you miss a pedestrian appearing from the opposite side. What should you change on retry?",
        "choices": [
          "Keep staring at the first vehicle until it fully clears",
          "Click continuously while focused on the first vehicle",
          "Ignore slowing vehicles because pedestrians are more important",
          "Widen your scan and keep checking the full conflict area"
        ],
        "answer": 3,
        "explanation": "A visible cue can matter, but over-focusing on one object can cause you to miss a second developing hazard.",
        "errorCategory": "Over-focus"
      },
      {
        "id": "g07-q05",
        "title": "Late click",
        "prompt": "You clicked late because you waited until the hazard was directly in front of the vehicle. Which retry strategy is best?",
        "choices": [
          "Click much earlier whenever any object appears",
          "Skip the clip and move on without review",
          "Identify the first moment the road user's intent affects your path",
          "Click only after the simulator confirms the correct answer"
        ],
        "answer": 2,
        "explanation": "The goal is to find the start of the developing hazard window. Waiting until the conflict is obvious usually means the response is late.",
        "errorCategory": "Late timing"
      },
      {
        "id": "g07-q06",
        "title": "Useful miss classification",
        "prompt": "After a missed simulator hazard, you want to classify the error. Which note is most useful?",
        "choices": [
          "Bad clip",
          "Occlusion: parked vehicles blocked the view until the road user emerged",
          "Missed it",
          "I need to react faster"
        ],
        "answer": 1,
        "explanation": "A useful debrief names the cause of the miss. Specific categories make practice transferable across clips.",
        "errorCategory": "Error classification"
      },
      {
        "id": "g07-q07",
        "title": "Shrinking space",
        "prompt": "In a simulator clip, you notice your lane position is tight near parked vehicles and an oncoming vehicle reduces available space. What should you recognize?",
        "choices": [
          "There is no hazard unless someone steps into the road",
          "You should click only for pedestrians and cyclists",
          "The only important cue is the speed limit",
          "A space-management hazard may be developing even without sudden movement"
        ],
        "answer": 3,
        "explanation": "A developing hazard can come from shrinking space, not just from a person or vehicle suddenly entering the lane.",
        "errorCategory": "Space cushion"
      },
      {
        "id": "g07-q08",
        "title": "Transfer to real driving",
        "prompt": "You finish the seven simulator clips and want to transfer the practice to real driving. Which habit is most useful?",
        "choices": [
          "Scan for hidden space, intent cues, changing speed, and shrinking space before a conflict becomes urgent",
          "Click mentally whenever any object appears",
          "Wait until a hazard is directly in front of you before reacting",
          "Treat simulator clips as a game unrelated to real driving"
        ],
        "answer": 0,
        "explanation": "Simulator practice should build real-world anticipation: reading cues early, preparing smoothly, and avoiding late reactions.",
        "errorCategory": "Real-driving transfer"
      }
    ]
  },
  {
    "id": "g08",
    "title": "G8 DVSA Format Transfer + First Paid Calibration",
    "passTarget": 80,
    "source": "assets/mcq-g08-dvsa-format-transfer-first-paid-calibration.md",
    "questions": [
      {
        "id": "g08-q01",
        "title": "Potential pedestrian",
        "prompt": "You are watching a DVSA-style clip. A pedestrian is standing on the sidewalk near a parked car. They have not moved toward the road yet. What should you do?",
        "choices": [
          "Click immediately because any pedestrian is a developing hazard",
          "Keep watching the pedestrian and nearby hidden space, but wait for movement that affects your driving",
          "Ignore the pedestrian unless they enter your lane",
          "Click repeatedly until the pedestrian moves"
        ],
        "answer": 1,
        "explanation": "A potential hazard becomes a developing hazard when it changes so that you may need to slow, change position, or stop.",
        "errorCategory": "Potential-vs-developing timing"
      },
      {
        "id": "g08-q02",
        "title": "Cyclist moving around a parked vehicle",
        "prompt": "A cyclist ahead is riding steadily near the curb. A few seconds later, they look over their shoulder and begin moving outward around a parked vehicle. When is the best DVSA-style click?",
        "choices": [
          "When the cyclist first appears in the scene",
          "When the cyclist starts moving outward and may affect your path",
          "When the cyclist is still riding steadily at the curb",
          "Only after you would need emergency braking"
        ],
        "answer": 1,
        "explanation": "The developing hazard starts when the cyclist's action begins to create a possible conflict with your driving path.",
        "errorCategory": "Developing-hazard recognition"
      },
      {
        "id": "g08-q03",
        "title": "Too-early click",
        "prompt": "You see a parked van near a crosswalk. It blocks your view, but no person or vehicle has emerged yet. You click at the first sight of the van and receive no score for the hazard. What most likely happened?",
        "choices": [
          "The van was never relevant to hazard perception",
          "DVSA clips only score vehicle hazards",
          "The click was too early because the hazard had not started developing",
          "You should have clicked continuously from the start"
        ],
        "answer": 2,
        "explanation": "Blocked sightlines are important to monitor, but scoring usually begins when a hazard develops, not merely when a possible hazard exists.",
        "errorCategory": "Early click"
      },
      {
        "id": "g08-q04",
        "title": "Too-late click",
        "prompt": "In a clip, a child steps from behind a parked car toward the road. You notice but wait until the child is directly in front of your vehicle before clicking. What is the main problem?",
        "choices": [
          "You clicked too early",
          "You should not click for pedestrians",
          "You clicked too late and likely missed the higher scoring part of the window",
          "You should click only after the vehicle has stopped"
        ],
        "answer": 2,
        "explanation": "DVSA scoring rewards recognizing the developing hazard early enough to respond smoothly. Waiting until the conflict is obvious reduces or loses credit.",
        "errorCategory": "Late click"
      },
      {
        "id": "g08-q05",
        "title": "Pattern clicking in DVSA format",
        "prompt": "During a scored DVSA session, you click every two seconds throughout the clip to avoid missing the hazard. What is the risk of this strategy?",
        "choices": [
          "It guarantees a high score because one click will land in the window",
          "It is required because each clip has many scored hazards",
          "It is safer than watching for changes in the scene",
          "It may be treated as pattern clicking and does not show real hazard judgment"
        ],
        "answer": 3,
        "explanation": "Clicks should be tied to observed hazard development. Regular pattern clicking can be penalized and weakens the training value.",
        "errorCategory": "Pattern clicking"
      },
      {
        "id": "g08-q06",
        "title": "First paid session",
        "prompt": "You are starting your first paid DVSA online scored session after using the free clips and explainer. What is the best goal for this first session?",
        "choices": [
          "Click as often as possible to learn the scoring system",
          "Pause after every possible hazard and look up the answer",
          "Focus only on getting a perfect score before moving on",
          "Treat it as calibration: use your normal strategy and record where your misses happen"
        ],
        "answer": 3,
        "explanation": "The first scored session is most useful as a baseline. It should reveal whether errors are early clicks, late clicks, missed occlusions, or overclicking.",
        "errorCategory": "Calibration mindset"
      },
      {
        "id": "g08-q07",
        "title": "Reviewing weak clips",
        "prompt": "After the first scored session, you review 6 clips where your score was weak. What is the most useful review method?",
        "choices": [
          "Sort each miss by category, such as early click, late click, missed hidden-space cue, or pattern clicking",
          "Memorize the exact second of each correct click",
          "Rewatch only the highest scoring clips",
          "Assume every miss came from the same cause"
        ],
        "answer": 0,
        "explanation": "Reviewing a small set by error category turns the scored session into targeted practice instead of score chasing.",
        "errorCategory": "Review by category"
      },
      {
        "id": "g08-q08",
        "title": "Distractors vs scored hazard",
        "prompt": "A clip contains several potential hazards: parked cars, a side road, and pedestrians on the sidewalk. Only one hazard later develops when a vehicle begins emerging from the side road. What should your clicking reflect?",
        "choices": [
          "Click only when the side-road vehicle begins to create a real driving conflict",
          "Click once for every object that could possibly become a hazard",
          "Avoid clicking because there were too many possible hazards",
          "Click at the start of the clip before anything changes"
        ],
        "answer": 0,
        "explanation": "DVSA format requires attention to many potential hazards, but scoring depends on identifying the one that actually develops.",
        "errorCategory": "Distractor vs scored hazard"
      }
    ]
  },
  {
    "id": "g09",
    "title": "G9 DVSA Focused Practice: Occlusion + Intention",
    "passTarget": 80,
    "source": "assets/mcq-g09-dvsa-occlusion-intention.md",
    "questions": [
      {
        "id": "g09-q01",
        "title": "Pedestrian near a gap",
        "prompt": "You are driving along a street with parked cars on both sides. A pedestrian is visible on the sidewalk, walking toward a gap between two parked vehicles near a crosswalk. What is the best hazard-perception response?",
        "choices": [
          "Wait until the pedestrian steps into the road before reacting",
          "Focus only on the vehicle ahead because pedestrians are still on the sidewalk",
          "Treat the gap as a blocked sightline and prepare for the pedestrian to emerge",
          "Move closer to the parked cars so you can see into the gap sooner"
        ],
        "answer": 2,
        "explanation": "Parked vehicles can hide a pedestrian until they are close to the lane. The gap and crosswalk make the pedestrian's possible path relevant before they step out.",
        "errorCategory": "Pedestrian occlusion"
      },
      {
        "id": "g09-q02",
        "title": "Bus at a crosswalk",
        "prompt": "A bus has stopped near a crosswalk. You cannot see the far side of the crosswalk or the sidewalk beyond the bus. What should you expect?",
        "choices": [
          "The bus blocks pedestrians from crossing, so the path is clear",
          "A pedestrian may appear from in front of or behind the bus",
          "The only hazard is whether the bus starts moving again",
          "You should move left quickly to pass before traffic builds up"
        ],
        "answer": 1,
        "explanation": "Large vehicles create major blind zones. A pedestrian can be hidden by the bus and enter the road before you have a clear view.",
        "errorCategory": "Large-vehicle blocked sightline"
      },
      {
        "id": "g09-q03",
        "title": "Bend with hedges",
        "prompt": "You are approaching a bend on a narrow road. The road disappears behind hedges, and you cannot see whether there is a stopped vehicle, cyclist, or pedestrian beyond the curve. What should you do?",
        "choices": [
          "Keep speed steady because no hazard is visible yet",
          "Move toward the center of the road to see farther around the bend",
          "Position and slow so you can stop within the distance you can see",
          "Wait for another driver to come through first, then follow their path"
        ],
        "answer": 2,
        "explanation": "A bend limits the visible stopping distance. Hidden hazards beyond the curve matter even before anything appears.",
        "errorCategory": "Bend occlusion"
      },
      {
        "id": "g09-q04",
        "title": "Crest of a hill",
        "prompt": "You are approaching the crest of a hill. You can see the road surface near you, but not the traffic, pedestrians, or side roads beyond the crest. What is the safest interpretation?",
        "choices": [
          "The road is clear because the visible section is clear",
          "The crest is a blocked sightline, so reduce risk before the hidden area opens",
          "Accelerate slightly to spend less time where visibility is poor",
          "Move right to improve your view over the hill"
        ],
        "answer": 1,
        "explanation": "A crest hides what is beyond it. Speed should match the distance you can see and react to.",
        "errorCategory": "Crest occlusion"
      },
      {
        "id": "g09-q05",
        "title": "Wheel angle without signal",
        "prompt": "A car ahead is near the centerline at a side road. Its left wheels are angled slightly toward the side road, but the turn signal is off. What is the best prediction?",
        "choices": [
          "It will definitely continue straight because there is no signal",
          "It is safe to overtake because the driver did not signal",
          "The wheel angle does not matter unless the brake lights are on",
          "It may turn left despite no signal, so prepare for slowing or stopping"
        ],
        "answer": 3,
        "explanation": "Wheel angle and lane position can reveal intention before or without a signal. Do not rely only on indicators.",
        "errorCategory": "Wheel-angle intention cue"
      },
      {
        "id": "g09-q06",
        "title": "Braking and body language",
        "prompt": "A vehicle ahead is approaching a driveway. Its brake lights come on, it drifts slightly toward the curb, and the driver turns their head toward the driveway. What should you expect?",
        "choices": [
          "The vehicle may turn or stop, even if no turn signal is showing",
          "The vehicle is only adjusting lane position and will continue normally",
          "The driver is checking mirrors, so you can maintain speed",
          "The vehicle cannot turn unless it first signals for several seconds"
        ],
        "answer": 0,
        "explanation": "Braking, curbward lane position, and body language can combine into a strong intention cue. The hazard is developing before the turn begins.",
        "errorCategory": "Body-language and braking cue"
      },
      {
        "id": "g09-q07",
        "title": "Cancelled signal",
        "prompt": "You are following a car on a busy street. It signals right, slows, then the signal cancels. A moment later, the vehicle begins moving toward the curb again near a side road. What should you do?",
        "choices": [
          "Watch for a second signal or turn movement and leave space",
          "Assume the cancelled signal means the driver will continue straight",
          "Close the gap because the driver has made a decision",
          "Move left immediately without checking mirrors"
        ],
        "answer": 0,
        "explanation": "A cancelled signal does not always mean the intention is gone. Drivers may hesitate, miss a turn, or signal again near the next opening.",
        "errorCategory": "Second-signal anticipation"
      },
      {
        "id": "g09-q08",
        "title": "Cyclist shifts left",
        "prompt": "You are approaching a side road partly hidden by parked vans. A cyclist is visible ahead, riding near the curb. The cyclist checks over their shoulder and shifts slightly left. What is the most likely risk?",
        "choices": [
          "The cyclist is making room for you to pass immediately",
          "The parked vans are irrelevant because the cyclist is visible",
          "The cyclist must stop before changing position",
          "The cyclist may be preparing to avoid a hidden obstruction or turn across your path"
        ],
        "answer": 3,
        "explanation": "A shoulder check, lane shift, and blocked side-road area suggest possible movement or conflict. The visible cyclist and hidden space both matter.",
        "errorCategory": "Vulnerable-road-user intention cue"
      }
    ]
  },
  {
    "id": "g10",
    "title": "G10 DVSA Conditions + Mock Checkpoint",
    "passTarget": 80,
    "source": "assets/mcq-g10-dvsa-conditions-mock-checkpoint.md",
    "questions": [
      {
        "id": "g10-q01",
        "title": "Heavy rain",
        "prompt": "You are watching a hazard-perception clip in heavy rain. The road surface is wet, spray is coming from vehicles ahead, and a pedestrian is near the curb. What should change in your prediction?",
        "choices": [
          "Focus only on the pedestrian because rain does not affect hazard timing",
          "Expect longer stopping distance, reduced visibility, and earlier hazard development",
          "Click later because hazards are harder to see in rain",
          "Maintain normal following distance unless traffic stops"
        ],
        "answer": 1,
        "explanation": "Rain reduces grip and visibility, so hazards need earlier speed, space, and scanning adjustments.",
        "errorCategory": "Wet braking distance"
      },
      {
        "id": "g10-q02",
        "title": "Low sun and glare",
        "prompt": "A low winter sun is shining toward you. You can see traffic ahead, but glare makes the far crosswalk and side streets hard to read. What is the best response?",
        "choices": [
          "Keep normal speed because the main lane is visible",
          "Scan only the lane markings because pedestrians will be obvious",
          "Look away from the road until the glare passes",
          "Reduce speed, increase following distance, and treat unclear edges as possible hazard zones"
        ],
        "answer": 3,
        "explanation": "Glare lowers contrast and hides road users at edges, so you need more time and space before a hazard becomes obvious.",
        "errorCategory": "Glare and poor contrast"
      },
      {
        "id": "g10-q03",
        "title": "Night edge scanning",
        "prompt": "You are driving at night on a road with parked cars and side streets. Headlights show only part of the scene, and the sidewalk edge is dark. What should you be most alert for?",
        "choices": [
          "Only hazards directly inside your headlight beam",
          "Hidden pedestrians, cyclists, or vehicles emerging from low-visibility areas",
          "Speed changes only when another driver flashes headlights",
          "Road signs, because road users are easier to see at night"
        ],
        "answer": 1,
        "explanation": "Night driving narrows useful vision. Hazards can develop from dark edges before they are fully visible.",
        "errorCategory": "Night scanning"
      },
      {
        "id": "g10-q04",
        "title": "Snow near a bend",
        "prompt": "A clip shows snow piled along the curb, tire tracks in the lane, and a vehicle ahead approaching a bend. What is the safest prediction?",
        "choices": [
          "Snow matters only if it is actively falling",
          "The lane is safe because tire tracks prove grip is normal",
          "The vehicle ahead may brake or steer earlier, and your own stopping distance would be longer",
          "Hazards are easier to predict because everyone drives slowly"
        ],
        "answer": 2,
        "explanation": "Snow can reduce lane width, hide edges, and increase stopping distance even when traffic is moving.",
        "errorCategory": "Snow space management"
      },
      {
        "id": "g10-q05",
        "title": "Shaded ice",
        "prompt": "The road looks mostly clear, but shaded patches remain near an intersection after freezing weather. A car ahead begins slowing before the junction. What should you assume?",
        "choices": [
          "The driver is being overcautious, so prepare to pass",
          "Ice only matters if you can see white snow on the road",
          "Shaded areas may be icy, so expect reduced grip and earlier braking",
          "The safest response is to brake sharply at the last second"
        ],
        "answer": 2,
        "explanation": "Ice can be hard to see, especially in shade. Junctions also collect braking and turning conflicts, so speed and space should adjust early.",
        "errorCategory": "Ice recognition"
      },
      {
        "id": "g10-q06",
        "title": "Poor contrast miss",
        "prompt": "During a DVSA adverse-conditions practice session, you miss a hazard because a dark-clothed pedestrian blends into a rainy background. How should you review the miss?",
        "choices": [
          "Classify it as poor contrast, then look for earlier context cues such as crossings, bus stops, and road edges",
          "Mark it as bad luck and move on",
          "Memorize the exact second when the pedestrian appeared",
          "Decide the clip was unfair because the pedestrian was hard to see"
        ],
        "answer": 0,
        "explanation": "Reviewing by error type helps transfer learning to new clips. Poor contrast should make you scan likely emergence zones earlier.",
        "errorCategory": "Mock review by error type"
      },
      {
        "id": "g10-q07",
        "title": "Score chasing",
        "prompt": "In a mock test, you clicked every possible hazard very early and scored poorly on several clips. What is the best adjustment?",
        "choices": [
          "Click only after the hazard is directly in your lane",
          "Stop clicking uncertain hazards entirely",
          "Click repeatedly whenever visibility is poor",
          "Identify potential hazards early, but click when one starts developing and affects the driver"
        ],
        "answer": 3,
        "explanation": "Hazard perception is not about clicking everything. The score depends on recognizing when a potential hazard becomes developing.",
        "errorCategory": "Score chasing"
      },
      {
        "id": "g10-q08",
        "title": "Inconsistent mock scores",
        "prompt": "Across several mock tests, your scores vary widely. You do well in daylight clips but miss hazards in rain, night, and glare. What is the best next step?",
        "choices": [
          "Review misses by condition and build a consistent routine: speed, space, scan, then click developing hazards",
          "Keep taking random mock tests until one score is high enough",
          "Practice only the clips you already score well on",
          "Click earlier in every clip regardless of what changes"
        ],
        "answer": 0,
        "explanation": "Consistency comes from a repeatable method, not from optimizing for one passing score. Conditions should trigger specific speed, space, and scan changes.",
        "errorCategory": "Consistency and condition transfer"
      }
    ]
  }
];
