const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");

const groups = [
  ["g01", "assets/mcq-g01-hidden-risk-baseline.md"],
  ["g02", "assets/mcq-g02-residential-sightlines-and-space.md"],
  ["g03", "assets/mcq-g03-intersection-scanning-ladder.md"],
  ["g04", "assets/mcq-g04-conflict-checks-around-the-car.md"],
  ["g05", "assets/mcq-g05-lane-change-deep-dive.md"],
  ["g06", "assets/mcq-g06-high-speed-large-vehicle-low-visibility.md"],
  ["g07", "assets/mcq-g07-us-simulator-set.md"],
  ["g08", "assets/mcq-g08-dvsa-format-transfer-first-paid-calibration.md"],
  ["g09", "assets/mcq-g09-dvsa-occlusion-intention.md"],
  ["g10", "assets/mcq-g10-dvsa-conditions-mock-checkpoint.md"]
];

function parseBank(groupId, assetPath) {
  const text = fs.readFileSync(path.join(root, assetPath), "utf8").replace(/\r\n/g, "\n");
  const title = text.match(/^# MCQ Bank:\s*(.+)$/m)?.[1] || groupId.toUpperCase();
  const passTarget = Number(text.match(/^Pass target:\s*(\d+)%/m)?.[1] || 80);
  const questionBlocks = text.split(/\n(?=## Q\d+\.)/).slice(1);
  const answerKey = new Map(
    [...text.matchAll(/^(\d+)\. ([A-D])$/gm)].map((match) => [Number(match[1]), match[2]])
  );

  const questions = questionBlocks.map((block, index) => {
    const number = index + 1;
    const headingMatch = block.match(/^## Q(\d+)\.\s*(.+)$/m);
    if (!headingMatch) {
      throw new Error(`${assetPath}: missing heading for question ${number}`);
    }

    const answerMatch = block.match(/\*\*Answer:\*\*\s*([A-D])/);
    const explanationMatch = block.match(/\*\*Explanation:\*\*\s*([\s\S]*?)\n\*\*Error category:\*\*/);
    const categoryMatch = block.match(/\*\*Error category:\*\*\s*(.+)/);
    if (!answerMatch || !explanationMatch || !categoryMatch) {
      throw new Error(`${assetPath}: missing metadata for question ${number}`);
    }

    const beforeAnswer = block.slice(0, block.indexOf("**Answer:**")).trim();
    const prompt = beforeAnswer.replace(/^## Q\d+\.\s*.+\n+/, "").replace(/\nA\.\s+[\s\S]*$/, "").trim();
    const choices = [...beforeAnswer.matchAll(/^[A-D]\.\s+(.+)$/gm)].map((match) => match[1].trim());
    if (choices.length !== 4) {
      throw new Error(`${assetPath}: question ${number} has ${choices.length} choices`);
    }

    const keyAnswer = answerKey.get(number);
    if (keyAnswer !== answerMatch[1]) {
      throw new Error(`${assetPath}: answer key mismatch for question ${number}`);
    }

    return {
      id: `${groupId}-q${String(number).padStart(2, "0")}`,
      title: headingMatch[2].trim(),
      prompt,
      choices,
      answer: answerMatch[1].charCodeAt(0) - "A".charCodeAt(0),
      explanation: explanationMatch[1].trim(),
      errorCategory: categoryMatch[1].trim()
    };
  });

  if (questions.length !== answerKey.size) {
    throw new Error(`${assetPath}: questions=${questions.length} answerKey=${answerKey.size}`);
  }

  return {
    id: groupId,
    title,
    passTarget,
    source: assetPath,
    questions
  };
}

const checkpoints = groups.map(([groupId, assetPath]) => parseBank(groupId, assetPath));
const output = `// Generated by scripts/generate_mcq_data.js from assets/mcq-g*.md.\nwindow.HPT_CHECKPOINTS = ${JSON.stringify(checkpoints, null, 2)};\n`;

fs.writeFileSync(path.join(root, "mcq-data.js"), output);
console.log(`Generated ${checkpoints.length} checkpoints with ${checkpoints.reduce((sum, item) => sum + item.questions.length, 0)} questions.`);
